version: '3'
services:

 ##########################################################
  rabbitmq:
    container_name: RabbitMQ
    image: rabbitmq:3-management-alpine
    volumes:
      - /mnt/teste/elk/storage/rabbitmq/storage/:/var/lib/rabbitmq/mnesia
    ports:
      - "15672:15672"
      - "5672:5672" 
    networks:
      - log
    environment:
      RABBITMQ_DEFAULT_USER: logUser
      RABBITMQ_DEFAULT_PASS: logPwd
      RABBITMQ_DEFAULT_VHOST: EnterpriseLog
  ##########################################################
  elasticsearch:
    container_name: ElasticSearch    
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.7.0
    environment: 
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - network.host=0.0.0.0
      - cluster.name="elastic_stack_logging"
      - node.name="elastic_stack_logging_data"
      - discovery.zen.minimum_master_nodes=1
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
    volumes: 
      - /mnt/teste/elk/elasticsearch/storage/:/usr/share/elasticsearch/data      
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD-SHELL", "curl -I -s -L http://localhost:9200 || exit 1"]
      interval: 30s
      timeout: 20s
      retries: 5     
    networks:
      - log
  ##########################################################
  kibana:
    container_name: Kibana    
    image: docker.elastic.co/kibana/kibana-oss:6.7.0
    environment:
      - server.name=kibana
      - server.host="0"
      - elasticsearch.url=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
    ports:
      - "5601:5601"
    healthcheck:
      test: ["CMD-SHELL", "curl -I -s -L http://localhost:5601/ || exit 1"]
      interval: 30s
      timeout: 20s
      retries: 5     
    networks:
      - log
  ##########################################################
  logstash:
    container_name: LogStash    
    image: docker.elastic.co/logstash/logstash-oss:6.7.0
    volumes:
      - ./logstash/config/:/config/
    links:
      - rabbitmq:AMQPServer
      - elasticsearch:elasticsearch
    networks:
      - log    
    command: bash -c "logstash-plugin install logstash-input-stomp && logstash -f /config"
    depends_on:
      - rabbitmq
      - elasticsearch
  ##########################################################
  metricbeat:
    container_name: metricbeat
    image: docker.elastic.co/beats/metricbeat-oss:6.7.0
    user: root
    volumes:
      - ./metricbeat/config/product.metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - elasticsearch
      - kibana
      - rabbitmq
    restart: on-failure
    networks:
      - log

networks:
  log:
    driver: bridge
