ARG ELK_VERSION

# https://github.com/elastic/beats/tree/master/metricbeat
FROM docker.elastic.co/beats/metricbeat-oss:${ELK_VERSION}

# Add your kibana plugins setup here
# RUN logstash-plugin install logstash-input-stomp
