ARG ELK_VERSION

# https://github.com/elastic/elasticsearch
FROM docker.elastic.co/elasticsearch/elasticsearch-oss:${ELK_VERSION}

# Add your kibana plugins setup here
# RUN logstash-plugin install logstash-input-stomp
